CREATE TABLE Users (
	[Id] BIGINT IDENTITY(1,1), 
	[Email] NVARCHAR(200) NOT NULL,
	[Password] NVARCHAR(200) NOT NULL,
	[Role] NVARCHAR(200) NOT NULL,
	[UserName] NVARCHAR(200) NOT NULL,
	CONSTRAINT PK_Users PRIMARY KEY ([Id]),
	CONSTRAINT UC_Email UNIQUE([Email]),
	CONSTRAINT UC_UserName UNIQUE([UserName])  
)