CREATE TABLE Users (
	[Id] BIGINT IDENTITY(1,1), 
	[Email] VARCHAR(200) NOT NULL,
	[Password] VARCHAR(200) NOT NULL,
	[Role] VARCHAR(200) NOT NULL,
	[UserName] VARCHAR(200) NOT NULL,
	CONSTRAINT PK_Users PRIMARY KEY ([Id]),
	CONSTRAINT UC_Email UNIQUE([Email]),
	CONSTRAINT UC_UserName UNIQUE([UserName])  
)